characters = {
        'эмбер': 'https://wotpack.ru/luchshij-bild-dlja-jember-v-genshin-impact/',
        'кэйа': 'https://wotpack.ru/luchshij-bild-dlja-kjeja-v-genshin-impact/',
        'лиза': 'https://wotpack.ru/liza-v-genshin-impact-gajd-luchshie-bildy/',
        'беннет': 'https://wotpack.ru/luchshij-bild-dlja-benneta-v-genshin-impact/',
        'саю': 'https://wotpack.ru/luchshij-bild-dlja-saju-v-genshin-impact/',
        'сайно': 'https://wotpack.ru/sajno-v-genshin-impact-luchshij-bild/',
        'сяо': 'https://wotpack.ru/gajd-dlja-sjao-v-genshin-impact-luchshie-bildy-prokachka-svjazki/',
        'сара': 'https://wotpack.ru/sara-v-genshin-impact-gajd-luchshie-bildy/',
        'райден': 'https://wotpack.ru/luchshij-bild-dlja-baal-sjogun-rajdjen-v-genshin-impact/',
        'джинн': 'https://wotpack.ru/luchshij-bild-dlja-dzhin-v-genshin-impact/',
        'мона': 'https://wotpack.ru/genshin-impact-bild-na-monu-professionalnogo-astrologa/',
        'дилюк': 'https://wotpack.ru/genshin-impact-gajd-na-diljuka-bild-vozvyshenie-i-osnovnye-sborki/',
        'ке цин': 'https://wotpack.ru/gajd-dlja-kje-cin-v-genshin-impact/',
        'аль хайтам': 'https://wotpack.ru/al-hajtam-v-genshin-impact-luchshij-bild/',
        'нилу': 'https://wotpack.ru/nilu-v-genshin-impact-luchshij-bild/',
        'нахида': 'https://wotpack.ru/nahida-v-genshin-impact-luchshij-bild/',
        'джун ли': 'https://wotpack.ru/genshin-impact-bild-na-chzhun-li-vlastelina-kamnja/',
        'венти': 'https://wotpack.ru/genshin-impact-bild-na-venti-odnogo-iz-semi-arhontov/',
        'альбедо': 'https://wotpack.ru/genshin-impact-bild-na-albedo-genija-i-princa-mela/',
        'аяка': 'https://wotpack.ru/luchshij-bild-dlja-ajaki-v-genshin-impact/',
        'аято': 'https://wotpack.ru/ajato-v-genshin-impact-luchshij-bild/',
        'бай чжу': 'https://wotpack.ru/baj-chzhu-v-genshin-impact-luchshij-bild/',
        'барбара': '',
        'бэй доу': '',
        'гань юй': '',
        'горо': '',
        'диона': '',
        'дори': '',
        'дехья': '',
        'е лань': '',
        'ёимия': '',
        'Итто': '',
        'кавех': '',
        'кадзуха': '',
        'кандакия': '',
        'кирара': '',
        'кли': '',
        'кокоми': '',
        'коллеи': '',
        'лайла': '',
        'мика': '',
        'нин гуан': '',
        'ноэлль': '',
        'розария': '',
        'рейзор': '',
        'сахароза': '',
        'синь цю': '',
        'куки': '',
        'синь янь': '',
        'странник': '',
        'сян лин': '',
        'тарталия': '',
        'тигнари': '',
        'тома': '',
        'фарузан': '',
        'фишль': '',
        'ху тао': '',
        'хейдзо': '',
        'ци ци': '',
        'чун юнь': '',
        'шень хэ': '',
        'элой': '',
        'эола': '',
        'юнь цзынь': '',
        'янь фей': '',
        'яо яо': '',
        'яэ мико': '',

    }